### PR TITLE
update hello.js to test github actions

### PR DESCRIPTION
**Pull request by avpeery**
Test github actions

### CODE REVIEW

**Comment by avpeery** [comment]
Trigger github actions flow

**Comment by avpeery** [comment]
Test

**Comment by avpeery** [comment]
Should pass

**Comment by avpeery** [comment]
@snailbones if you have time, do you think you can get this PR review to test out the github actions workflow? github doesn't allow you to approve your own PR's. Thanks so much!

**Review by SnailBones — APPROVED** [review]
Excellent work removing excessive punctuation 🎉

**Comment by avpeery** [comment]
Test

**Comment by avpeery** [comment]
test

**Comment by avpeery** [comment]
check

**Comment by avpeery** [comment]
test

**Review by derbyandlou — APPROVED** [review]

**Review by derbyandlou — APPROVED** [review]

**Pull request merged**
